### ISSUE TITLE
factory_boy dependecy and tests

### ISSUE THREAD

**Issue by thebigspoon** [Cadasta/ckanext-project#19]
Hey @joetsoi,
I'm trying to run the tests for this extension. I was hoping you could help me with this minor problem. 

I have ``factory_boy-2.5.2`` installed. I noticed that ``factory_boy`` is not a dependency in any of the extensions or ``ckan`` requirements files. But it seems to be a hard dependency in ckan's [factories test file](https://github.com/ckan/ckan/blob/master/ckan/tests/factories.py#L4-L7). 

If I run the ``test_validators.py`` module in this repo:
```python
nosetests --ckan --nologcapture --with-pylons=test.ini ckanext.project.tests.test_validators
```
Two of the tests fail with some weird output which seem to be talking about Django models. Any ideas how to get around these? Should I be using a different version of ``factory_boy``?
```python
======================================================================
ERROR: ckanext.project.tests.test_validators.TestOrganizationNameValidator.test_existing_name
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "<string>", line 3, in wrapper
  File "/usr/lib/ckan/default/src/ckanext-project/ckanext/project/tests/test_validators.py", line 54, in test_existing_name
    name='organization')
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/factory/base.py", line 81, in __call__
    return cls.create(**kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/factory/base.py", line 559, in create
    return cls._generate(True, attrs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/factory/base.py", line 475, in _generate
    "is either not set or False." % dict(f=cls.__name__))
FactoryError: Cannot generate instances of abstract factory Organization; Ensure Organization.Meta.model is set and Organization.Meta.abstract is either not set or False.

======================================================================
ERROR: ckanext.project.tests.test_validators.TestProjectNameValidator.test_existing_name
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "<string>", line 3, in wrapper
  File "/usr/lib/ckan/default/src/ckanext-project/ckanext/project/tests/test_validators.py", line 25, in test_existing_name
    name='organization')
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/factory/base.py", line 81, in __call__
    return cls.create(**kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/factory/base.py", line 559, in create
    return cls._generate(True, attrs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/factory/base.py", line 475, in _generate
    "is either not set or False." % dict(f=cls.__name__))
FactoryError: Cannot generate instances of abstract factory Organization; Ensure Organization.Meta.model is set and Organization.Meta.abstract is either not set or False.

----------------------------------------------------------------------
Ran 5 tests in 0.538s

FAILED (errors=2)
```

**Comment by thebigspoon** [comment]
CKAN uses ``factory-boy.2.1.1`` for tests to pass and I was using ``factory_boy.2.5.2`` which seems to be the Django counterpart. Closing
